# Generated by Django 4.2.6 on 2023-10-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
    ]
