# Generated by Django 4.2.6 on 2023-10-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
